<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20260814170000 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Ajoute les catégories produits et garantit un entrepôt unique par pays.';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE product_category (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(120) NOT NULL, slug VARCHAR(140) NOT NULL, position INT NOT NULL, active BOOLEAN NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_1E71339D989D9B62 ON product_category (slug)');
        $this->addSql('ALTER TABLE product ADD category_id INT DEFAULT NULL');
        $this->addSql('CREATE INDEX IDX_D34A04AD12469DE2 ON product (category_id)');
        $this->addSql("INSERT INTO product_category (name, slug, position, active) VALUES ('Gommages', 'gommages', 10, TRUE), ('Hydratants', 'hydratants', 20, TRUE)");
        $this->addSql("UPDATE product SET category_id = (SELECT id FROM product_category WHERE slug = 'gommages') WHERE slug = 'radiance-boosting-body-scrub' OR LOWER(type) LIKE '%gommage%'");
        $this->addSql("UPDATE product SET category_id = (SELECT id FROM product_category WHERE slug = 'hydratants') WHERE category_id IS NULL");
        $this->addSql('ALTER TABLE product ALTER category_id SET NOT NULL');
        $this->addSql('ALTER TABLE product ADD CONSTRAINT FK_D34A04AD12469DE2 FOREIGN KEY (category_id) REFERENCES product_category (id) ON DELETE RESTRICT NOT DEFERRABLE');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_ECB38BFCF026BB7C ON warehouse (country_code)');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('DROP INDEX UNIQ_ECB38BFCF026BB7C');
        $this->addSql('ALTER TABLE product DROP CONSTRAINT FK_D34A04AD12469DE2');
        $this->addSql('DROP INDEX IDX_D34A04AD12469DE2');
        $this->addSql('ALTER TABLE product DROP category_id');
        $this->addSql('DROP TABLE product_category');
    }
}
