<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260814123305 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE inventory (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, quantity_on_hand INT NOT NULL, quantity_reserved INT NOT NULL, low_stock_threshold INT NOT NULL, product_id INT NOT NULL, warehouse_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_B12D4A364584665A ON inventory (product_id)');
        $this->addSql('CREATE INDEX IDX_B12D4A365080ECDE ON inventory (warehouse_id)');
        $this->addSql('CREATE UNIQUE INDEX uniq_product_warehouse ON inventory (product_id, warehouse_id)');
        $this->addSql('CREATE TABLE market (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, country_code VARCHAR(2) NOT NULL, name VARCHAR(100) NOT NULL, currency_code VARCHAR(3) NOT NULL, active BOOLEAN NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_6BAC85CBF026BB7C ON market (country_code)');
        $this->addSql('CREATE TABLE market_price (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, amount_minor INT DEFAULT NULL, published BOOLEAN NOT NULL, product_id INT NOT NULL, market_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_1E69DAC4584665A ON market_price (product_id)');
        $this->addSql('CREATE INDEX IDX_1E69DAC622F3F37 ON market_price (market_id)');
        $this->addSql('CREATE UNIQUE INDEX uniq_product_market ON market_price (product_id, market_id)');
        $this->addSql('CREATE TABLE product (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, slug VARCHAR(160) NOT NULL, name VARCHAR(200) NOT NULL, type VARCHAR(120) NOT NULL, size VARCHAR(40) NOT NULL, short_description TEXT NOT NULL, description TEXT NOT NULL, benefits JSON NOT NULL, ingredients JSON NOT NULL, usage_instructions TEXT NOT NULL, image_path VARCHAR(255) NOT NULL, image_position VARCHAR(16) NOT NULL, active BOOLEAN NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_D34A04AD989D9B62 ON product (slug)');
        $this->addSql('CREATE TABLE warehouse (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, code VARCHAR(40) NOT NULL, name VARCHAR(120) NOT NULL, country_code VARCHAR(2) NOT NULL, central BOOLEAN NOT NULL, active BOOLEAN NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_ECB38BFC77153098 ON warehouse (code)');
        $this->addSql('CREATE TABLE messenger_messages (id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, body TEXT NOT NULL, headers TEXT NOT NULL, queue_name VARCHAR(190) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, available_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, delivered_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_75EA56E0FB7336F0E3BD61CE16BA31DBBF396750 ON messenger_messages (queue_name, available_at, delivered_at, id)');
        $this->addSql('ALTER TABLE inventory ADD CONSTRAINT FK_B12D4A364584665A FOREIGN KEY (product_id) REFERENCES product (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE inventory ADD CONSTRAINT FK_B12D4A365080ECDE FOREIGN KEY (warehouse_id) REFERENCES warehouse (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE market_price ADD CONSTRAINT FK_1E69DAC4584665A FOREIGN KEY (product_id) REFERENCES product (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE market_price ADD CONSTRAINT FK_1E69DAC622F3F37 FOREIGN KEY (market_id) REFERENCES market (id) ON DELETE CASCADE NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE inventory DROP CONSTRAINT FK_B12D4A364584665A');
        $this->addSql('ALTER TABLE inventory DROP CONSTRAINT FK_B12D4A365080ECDE');
        $this->addSql('ALTER TABLE market_price DROP CONSTRAINT FK_1E69DAC4584665A');
        $this->addSql('ALTER TABLE market_price DROP CONSTRAINT FK_1E69DAC622F3F37');
        $this->addSql('DROP TABLE inventory');
        $this->addSql('DROP TABLE market');
        $this->addSql('DROP TABLE market_price');
        $this->addSql('DROP TABLE product');
        $this->addSql('DROP TABLE warehouse');
        $this->addSql('DROP TABLE messenger_messages');
    }
}
