<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20260815090000 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Ajoute les transferts de stock entre l’entrepôt central et les dépôts locaux.';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE stock_transfer (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, source_warehouse_id INT NOT NULL, destination_warehouse_id INT NOT NULL, reference VARCHAR(40) NOT NULL, status VARCHAR(20) NOT NULL, notes TEXT DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, shipped_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, received_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_STOCK_TRANSFER_REFERENCE ON stock_transfer (reference)');
        $this->addSql('CREATE INDEX IDX_STOCK_TRANSFER_SOURCE ON stock_transfer (source_warehouse_id)');
        $this->addSql('CREATE INDEX IDX_STOCK_TRANSFER_DESTINATION ON stock_transfer (destination_warehouse_id)');
        $this->addSql('CREATE TABLE stock_transfer_item (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, stock_transfer_id INT NOT NULL, product_id INT NOT NULL, quantity INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_STOCK_TRANSFER_ITEM_TRANSFER ON stock_transfer_item (stock_transfer_id)');
        $this->addSql('CREATE INDEX IDX_STOCK_TRANSFER_ITEM_PRODUCT ON stock_transfer_item (product_id)');
        $this->addSql('CREATE UNIQUE INDEX uniq_transfer_product ON stock_transfer_item (stock_transfer_id, product_id)');
        $this->addSql('ALTER TABLE stock_transfer ADD CONSTRAINT FK_STOCK_TRANSFER_SOURCE FOREIGN KEY (source_warehouse_id) REFERENCES warehouse (id) ON DELETE RESTRICT NOT DEFERRABLE');
        $this->addSql('ALTER TABLE stock_transfer ADD CONSTRAINT FK_STOCK_TRANSFER_DESTINATION FOREIGN KEY (destination_warehouse_id) REFERENCES warehouse (id) ON DELETE RESTRICT NOT DEFERRABLE');
        $this->addSql('ALTER TABLE stock_transfer_item ADD CONSTRAINT FK_STOCK_TRANSFER_ITEM_TRANSFER FOREIGN KEY (stock_transfer_id) REFERENCES stock_transfer (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE stock_transfer_item ADD CONSTRAINT FK_STOCK_TRANSFER_ITEM_PRODUCT FOREIGN KEY (product_id) REFERENCES product (id) ON DELETE RESTRICT NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('ALTER TABLE stock_transfer_item DROP CONSTRAINT FK_STOCK_TRANSFER_ITEM_TRANSFER');
        $this->addSql('ALTER TABLE stock_transfer_item DROP CONSTRAINT FK_STOCK_TRANSFER_ITEM_PRODUCT');
        $this->addSql('ALTER TABLE stock_transfer DROP CONSTRAINT FK_STOCK_TRANSFER_SOURCE');
        $this->addSql('ALTER TABLE stock_transfer DROP CONSTRAINT FK_STOCK_TRANSFER_DESTINATION');
        $this->addSql('DROP TABLE stock_transfer_item');
        $this->addSql('DROP TABLE stock_transfer');
    }
}
