<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260814132158 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE payment (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, status VARCHAR(30) NOT NULL, amount_minor INT NOT NULL, currency_code VARCHAR(3) NOT NULL, external_reference VARCHAR(160) DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, customer_order_id INT NOT NULL, method_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_6D28840DA15A2E17 ON payment (customer_order_id)');
        $this->addSql('CREATE INDEX IDX_6D28840D19883967 ON payment (method_id)');
        $this->addSql('CREATE TABLE payment_method (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, code VARCHAR(60) NOT NULL, name VARCHAR(160) NOT NULL, type VARCHAR(30) NOT NULL, fulfillment_scope VARCHAR(20) NOT NULL, instructions TEXT DEFAULT NULL, active BOOLEAN NOT NULL, market_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_7B61A1F6622F3F37 ON payment_method (market_id)');
        $this->addSql('CREATE UNIQUE INDEX uniq_payment_market_code ON payment_method (market_id, code)');
        $this->addSql('ALTER TABLE payment ADD CONSTRAINT FK_6D28840DA15A2E17 FOREIGN KEY (customer_order_id) REFERENCES customer_order (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE payment ADD CONSTRAINT FK_6D28840D19883967 FOREIGN KEY (method_id) REFERENCES payment_method (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE payment_method ADD CONSTRAINT FK_7B61A1F6622F3F37 FOREIGN KEY (market_id) REFERENCES market (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE customer_order ADD payment_method_name VARCHAR(160) NOT NULL');
        $this->addSql('ALTER TABLE customer_order ADD payment_method_type VARCHAR(30) NOT NULL');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE payment DROP CONSTRAINT FK_6D28840DA15A2E17');
        $this->addSql('ALTER TABLE payment DROP CONSTRAINT FK_6D28840D19883967');
        $this->addSql('ALTER TABLE payment_method DROP CONSTRAINT FK_7B61A1F6622F3F37');
        $this->addSql('DROP TABLE payment');
        $this->addSql('DROP TABLE payment_method');
        $this->addSql('ALTER TABLE customer_order DROP payment_method_name');
        $this->addSql('ALTER TABLE customer_order DROP payment_method_type');
    }
}
