<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20260815100000 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Ajoute le journal des mouvements de stock et initialise les soldes existants.';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE stock_movement (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, movement_type VARCHAR(40) NOT NULL, quantity_on_hand_delta INT NOT NULL, quantity_reserved_delta INT NOT NULL, balance_on_hand INT NOT NULL, balance_reserved INT NOT NULL, reference VARCHAR(80) DEFAULT NULL, description VARCHAR(255) NOT NULL, performed_by VARCHAR(180) DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, product_id INT NOT NULL, warehouse_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_BB1BC1B54584665A ON stock_movement (product_id)');
        $this->addSql('CREATE INDEX IDX_BB1BC1B55080ECDE ON stock_movement (warehouse_id)');
        $this->addSql('ALTER TABLE stock_movement ADD CONSTRAINT FK_BB1BC1B54584665A FOREIGN KEY (product_id) REFERENCES product (id) ON DELETE RESTRICT NOT DEFERRABLE');
        $this->addSql('ALTER TABLE stock_movement ADD CONSTRAINT FK_BB1BC1B55080ECDE FOREIGN KEY (warehouse_id) REFERENCES warehouse (id) ON DELETE RESTRICT NOT DEFERRABLE');
        $this->addSql("INSERT INTO stock_movement (movement_type, quantity_on_hand_delta, quantity_reserved_delta, balance_on_hand, balance_reserved, reference, description, performed_by, created_at, product_id, warehouse_id) SELECT 'opening_balance', quantity_on_hand, quantity_reserved, quantity_on_hand, quantity_reserved, NULL, 'Solde initial lors de l’activation du journal des stocks.', 'system', CURRENT_TIMESTAMP, product_id, warehouse_id FROM inventory");
    }

    public function down(Schema $schema): void
    {
        $this->addSql('ALTER TABLE stock_movement DROP CONSTRAINT FK_BB1BC1B54584665A');
        $this->addSql('ALTER TABLE stock_movement DROP CONSTRAINT FK_BB1BC1B55080ECDE');
        $this->addSql('DROP TABLE stock_movement');
    }
}
