<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260814125713 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE customer_order (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, reference VARCHAR(30) NOT NULL, status VARCHAR(30) NOT NULL, customer_name VARCHAR(160) NOT NULL, email VARCHAR(180) NOT NULL, phone VARCHAR(40) NOT NULL, address_line TEXT NOT NULL, city VARCHAR(120) NOT NULL, currency_code VARCHAR(3) NOT NULL, subtotal_minor INT NOT NULL, shipping_minor INT NOT NULL, total_minor INT NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, market_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_3B1CE6A3AEA34913 ON customer_order (reference)');
        $this->addSql('CREATE INDEX IDX_3B1CE6A3622F3F37 ON customer_order (market_id)');
        $this->addSql('CREATE TABLE order_item (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, product_name VARCHAR(200) NOT NULL, unit_price_minor INT NOT NULL, quantity INT NOT NULL, total_minor INT NOT NULL, customer_order_id INT NOT NULL, product_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_52EA1F09A15A2E17 ON order_item (customer_order_id)');
        $this->addSql('CREATE INDEX IDX_52EA1F094584665A ON order_item (product_id)');
        $this->addSql('CREATE TABLE shipping_rate (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, city VARCHAR(120) NOT NULL, amount_minor INT NOT NULL, minimum_days INT NOT NULL, maximum_days INT NOT NULL, active BOOLEAN NOT NULL, market_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_4E50A93B622F3F37 ON shipping_rate (market_id)');
        $this->addSql('CREATE UNIQUE INDEX uniq_shipping_market_city ON shipping_rate (market_id, city)');
        $this->addSql('ALTER TABLE customer_order ADD CONSTRAINT FK_3B1CE6A3622F3F37 FOREIGN KEY (market_id) REFERENCES market (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE order_item ADD CONSTRAINT FK_52EA1F09A15A2E17 FOREIGN KEY (customer_order_id) REFERENCES customer_order (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE order_item ADD CONSTRAINT FK_52EA1F094584665A FOREIGN KEY (product_id) REFERENCES product (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE shipping_rate ADD CONSTRAINT FK_4E50A93B622F3F37 FOREIGN KEY (market_id) REFERENCES market (id) ON DELETE CASCADE NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE customer_order DROP CONSTRAINT FK_3B1CE6A3622F3F37');
        $this->addSql('ALTER TABLE order_item DROP CONSTRAINT FK_52EA1F09A15A2E17');
        $this->addSql('ALTER TABLE order_item DROP CONSTRAINT FK_52EA1F094584665A');
        $this->addSql('ALTER TABLE shipping_rate DROP CONSTRAINT FK_4E50A93B622F3F37');
        $this->addSql('DROP TABLE customer_order');
        $this->addSql('DROP TABLE order_item');
        $this->addSql('DROP TABLE shipping_rate');
    }
}
